swagger: '2.0'
info:
  title: TAXI MIL API REST
  description: It is API to scooter app
  termsOfService: https://www.google.com/policies/terms/
  contact:
    email: misael.gonzalez.e.229@gmail.com
  license:
    name: BSD License
  version: v1
basePath: /appback/
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
security:
  - Basic: []
  - bearerAuth: []
# ====== PATHS =======
paths:
  # STATUS
  /api/v1/commons/invited_service_price/:
    post:
      operationId: calculate_invited_service_price_customer
      description: Calcular el precio del servicio para un invitado
      parameters:
        - name: body
          in: body
          description: Calcular el precio del servicio
          schema:
            $ref: '#/definitions/CalculatePriceOrderInvited'
      responses:
        '200':
          description: 'Precio previo del pedido'
      tags:
        - Común
  /api/v1/commons/status/:
    get:
      operationId: general_status_get
      description: Return all status.
      parameters: []
      responses:
        '200':
          description: 'Regresa todos los estatus que se ocupan de manera general'
      tags:
        - Común
    parameters: []
  /api/v1/commons/order_status/:
    get:
      operationId: orders_status_get
      description: Listado de status de ordenes.
      parameters: []
      responses:
        '200':
          description: 'Regresa todos los estatus que se ocupan para las ordenes'
      tags:
        - Común
    parameters: []